name: Robot Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TestSuite
        run: |  
          python3 tests/TestSuite.py
          robot --outputdir reports tests/smoke.robot

      - name: Run Dummy Step
        run: >
          echo "Hello from"
          echo "Hello from Github Actions"

      # - name: upload Robot Reports
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-reports
      #     path: |
      #       log.html
      #       output.xml
      #       report.html

      # to deploy reports:
      # 1- make repo public
      # 2- enable GitHub Pages
      # 3- in setting/pages, set source to github actions instead of main branch
      # 4- set permissions: read & write
      # 5- create index page
      # 6- after verifying reports generation, 
      #    set deploy env in deply step:
      #       environment:
      #       name: github-pages
      #       url: ${{ steps.deployment.outputs.page_url }}
      # note: github takes at least 5 mins. to populate the page site
      - name: Create index page
        run: |
          if [ -f reports/report.html ]; then
            cp reports/report.html reports/index.html
          else
            echo "report.html not found!"
            exit 1
          fi

      - name: Verify reports
        run: |
          pwd
          ls
          ls reports
          find reports

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to Github Pages
      id: deployment
      uses: actions/deploy-pages@v4
        